version: "3"
services:
  db:
    image: "kartoza/postgis"
    container_name: "fitness-jogger-db"
    # entrypoint: "apt-get -y install postgis"
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5444:5432"
    expose:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data
  server:
    build: fitness_jogger
    container_name: "fitness-service"
    entrypoint: ./entrypoint.sh
    depends_on:
      - "db"
    environment:
      - "PYTHONUNBUFFERED=1"
      - "DB_HOST=fitness-jogger-db"
      - "DB_NAME=postgres"
      - "DB_USER=docker"
      - "DB_PASSWORD=postgres"
      - "DB_PORT=5432"
      - "DEBUG=False"
    command: pipenv run gunicorn --workers=4 -b 0.0.0.0:8000 fitness_jogger.wsgi:application --access-logfile -
    ports:
      - "8000:8000"
    expose:
      - "8000"
volumes:
  database_data:
    driver: local