# Generated by Django 3.1.3 on 2020-11-27 18:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201124_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('time', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('weather', models.JSONField(null=True)),
            ],
        ),
    ]
