# Generated by Django 3.1.3 on 2020-11-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
